# Generated by Django 3.2.16 on 2023-01-03 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.EmailField(max_length=150, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=150, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Contact Message')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=150, verbose_name='Category name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_name', models.CharField(max_length=150, verbose_name='Testimonial Name')),
                ('testimonial_img', models.ImageField(upload_to='', verbose_name='Testimonial Image')),
                ('testimonial_contents', models.TextField(verbose_name='Testimonial Contents')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Property Title')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('img', models.ImageField(upload_to='', verbose_name='Property Featured Image')),
                ('floor_plan', models.ImageField(upload_to='', verbose_name='Floor Plan')),
                ('description', models.TextField(verbose_name='Post Contents')),
                ('price', models.IntegerField()),
                ('arv', models.IntegerField(blank=True, null=True)),
                ('gross_margin', models.IntegerField(blank=True, null=True)),
                ('year_build', models.IntegerField()),
                ('parking', models.CharField(choices=[('Driveway', 'Driveway')], default=0, max_length=30)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('sq_footage', models.CharField(max_length=100)),
                ('lot_size', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Sold', 'Sold')], default='Available', max_length=10)),
                ('property_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.propertytype', verbose_name='Post Category')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='app.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
