# Generated by Django 3.2.16 on 2023-01-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230105_2141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JointVenture',
        ),
    ]
