# Generated by Django 3.2.16 on 2023-01-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_jointventure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jointventure',
            old_name='agreement_img',
            new_name='agreement_document',
        ),
    ]
