# Generated by Django 3.2.16 on 2023-01-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_agreement_img_jointventure_agreement_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JointVenture',
        ),
    ]
