# Generated by Django 3.2.16 on 2023-01-05 14:14

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_jointventure'),
    ]

    operations = [
        migrations.CreateModel(
            name='JointVenture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=150, verbose_name='Email Address')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('company_name', models.CharField(max_length=150, verbose_name='Company Name')),
                ('property_address', models.CharField(max_length=150, verbose_name='Property Address')),
                ('sq_footage', models.CharField(max_length=100)),
                ('acquisition_price', models.IntegerField()),
                ('asking_price', models.IntegerField()),
                ('arv', models.IntegerField(blank=True, null=True)),
                ('year_build', models.IntegerField()),
                ('year_roof', models.IntegerField()),
                ('year_hvac', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('comp1_link', models.URLField()),
                ('comp1_price', models.IntegerField()),
                ('comp2_link', models.URLField(blank=True, null=True)),
                ('comp2_price', models.IntegerField(blank=True, null=True)),
                ('comp3_link', models.URLField(blank=True, null=True)),
                ('comp3_price', models.IntegerField(blank=True, null=True)),
                ('photo_link', models.URLField()),
                ('inspection_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
                ('occupancy', models.CharField(max_length=200)),
                ('hoa', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True)),
                ('how_much', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_plan', models.CharField(blank=True, choices=[('MONTHLY', 'MONTHLY'), ('QUATERLY', 'QUATERLY'), ('ANNUALLY', 'ANNUALLY')], max_length=8, null=True)),
                ('access', models.CharField(max_length=200)),
                ('date_aggreement', models.DateTimeField()),
                ('agreement_document', models.FileField(upload_to='', verbose_name='Original Purchase Agreement')),
                ('property_note', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
