# Generated by Django 3.2.16 on 2023-01-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_jointventure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointventure',
            name='agreement_document',
            field=models.FileField(upload_to='documents/', verbose_name='Original Purchase Agreement'),
        ),
    ]
