# Generated by Django 3.2.16 on 2023-01-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_jointventure_agreement_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link to video(vimeo)'),
        ),
        migrations.AlterField(
            model_name='jointventure',
            name='photo_link',
            field=models.URLField(max_length=500),
        ),
    ]
